"""Product keyword mapping for recommendation ranking."""

PRODUCT_KEYWORD_MAP = {
    "giay-nike-air-force-1-07-lx-lucky-charms": ["lucky charms", "air force 1 lx", "nike af1 lucky charms", "quà cho người yêu", "quà người yêu", "đặc biệt", "sưu tầm"],
    "giay-nike-air-force-1-07-m-all-white-cw2288-111": ["all white", "trắng basic", "đi học", "đi làm", "đi chơi", "dễ phối", "sneaker trắng", "giày công ty"],
    "giay-nike-air-force-1-07-white-gum": ["white gum", "đế gum", "trắng đế gum", "đi làm", "đi chơi", "basic", "dễ phối", "giày công ty"],
    "giay-nike-air-force-1-low-valentine-s-day-2023": ["valentine", "lễ tình nhân", "đỏ hồng", "quà người yêu", "quà cho người yêu", "romantic", "tặng bạn gái", "tặng bạn trai"],
    "giay-nike-air-force-1-shadow-infinite-lilac": ["infinite lilac", "tím", "trẻ trung", "nữ tính", "đi chơi", "đi học", "thời trang"],
    "giay-puma-rs-x-the-unity-collection": ["retro", "streetwear", "năng động", "đi chơi", "đi học", "puma rsx", "giày chạy"],
    "giay-puma-army-trainer-white-black": ["trắng đen", "basic", "đi học", "đi làm", "đi chơi", "dễ phối", "giày công ty"],
    "giay-puma-lifestyle-suede-black": ["suede black", "da lộn", "đen", "cổ điển", "basic", "đi làm", "đi chơi"],
    "giay-puma-skye-clean-pink": ["mẹ","hồng", "nữ tính", "dễ thương", "đi học", "đi chơi", "tặng mẹ", "tặng bạn gái","mother"],
    "giay-new-balance-530-retro-running-navy": ["running", "chạy bộ", "đi bộ", "navy", "êm", "thoáng khí", "retro", "giày chạy", "giày jogging"],
    "giay-bong-a-hitek": ["đá bóng", "bóng đá", "đá banh", "tf", "fg", "sân cỏ nhân tạo", "hitek", "tập luyện"],
    "giay-bong-a-jogarbola-kumo-fit": ["đá bóng", "bóng đá", "đá banh", "tf", "fg", "ôm cổ chân", "kumo fit", "sân cỏ nhân tạo"],
    "giay-a-bong-230727": ["đá bóng", "bóng đá", "đá banh", "tf", "fg", "mitre", "tập luyện", "sân cỏ nhân tạo"],
    "giay-the-thao-promax-muran": ["gym", "fitness", "cầu lông", "bóng chuyền", "muran", "thể thao", "đa dụng", "giày chạy"],
    "sereno-brogues-oxford-of37": ["bố", "công sở", "phỏng vấn", "lịch sự", "oxford", "đen", "nâu", "nam", "father", "giày công ty"],
    "sir-classic-oxford-of34": ["bố", "công sở", "chelsea boots", "lịch sự", "smart casual", "đi làm", "nam", "father"],
    "classy-chelsea-boots-bo14": ["bố", "đi làm", "đi chơi", "chelsea boots", "lịch sự", "sang trọng", "nam", "father", "giày công ty"],
    "giay-da-derby-nam-e-chunky-gnta51-5103-d": ["bố", "derby", "công sở", "phỏng vấn", "chỉnh chu", "nam", "đi làm", "father", "giày công ty"],
    "giay-puma-skye-clean-pink": ["mẹ", "nữ", "nữ tính", "hồng", "thanh lịch", "mother"],
    "giay-nike-air-force-1-shadow-infinite-lilac": ["mẹ", "nữ", "tím", "nữ tính", "đi chơi", "mother"],
    "giay-nike-air-force-1-07-m-all-white-cw2288-111": ["mẹ", "nữ", "trắng", "basic", "mother", "giày công ty"],
    "giay-nike-air-force-1-07-white-gum": ["mẹ", "nữ", "trắng", "be", "mother"],
    "giay-puma-army-trainer-white-black": ["bạn bè", "basic", "dễ phối", "friend", "giày chạy", "giày đi học"],
    "giay-puma-rs-x-the-unity-collection": ["bạn bè", "trẻ trung", "streetwear", "friend", "giày chạy"],
    "giay-new-balance-530-retro-running-navy": ["bạn bè", "retro", "running", "friend", "giày chạy", "giày jogging"],
}
